package cn.netdiscovery.ualist;

import cn.netdiscovery.core.Spider;
import cn.netdiscovery.core.domain.Request;
import cn.netdiscovery.core.downloader.file.FileDownloader;

import java.util.Arrays;
import java.util.stream.Collectors;

public class BaiduBaike {
    public static void main(String[] args) {

      Request[] requests=  Arrays.asList(data()).stream().map(s -> new Request("https://baike.baidu.com/item/"+s,"tom")).collect(Collectors.toList()).toArray(new Request[]{});
        Spider.create().name("tom").request(requests)
                .parser(new BaiduBaikeParser())
                .pipeline(new SaveImgPipeline())
                .run();
    }


    private static String[] data(){
        return new String[] {"美国白蛾",
        "舞毒蛾",
                "柳毒蛾",
                "侧柏毒蛾",
                "角斑古毒蛾",
                "油松毛虫",
                "杨枯叶蛾",
                "苹果枯叶蛾",
                "黄褐天幕毛虫",
                "褐带卷叶蛾",
                "顶梢卷叶蛾",
                "金纹细蛾",
                "桃潜叶蛾",
                "扁刺蛾",
                "黄刺蛾",
                "榆绿天蛾",
                "豆天蛾",
                "桃天蛾",
                "柳天蛾",
                "春尺蠖",
                "黄连木尺蠖",
                "枣尺蠖",
                "国槐尺蠖",
                "柿星尺蠖",
                "杨小舟蛾",
                "苹掌舟蛾",
                "双尾舟蛾",
                "杨扇舟蛾",
                "梨星毛虫",
                "花布灯蛾",
                "柑桔凤蝶",
                "榆蛱蝶",
                "草地螟",
                "黏虫",
                "黄杨绢野螟",
                "榆蓝叶甲",
                "柳蓝叶甲",
                "黄栌胫跳甲",
                "樗蚕蛾",
                "绿尾大蚕蛾",
                "大袋蛾",
                "柳瘿蜂",
                "杨直角叶蜂",
                "苹果巢蛾",
                "国槐小潜卷蛾",
                "核桃缀叶螟",
                "合欢巢蛾",
                "大青叶蝉",
                "黑蚱蝉",
                "桃一点叶蝉",
                "斑衣蜡蝉",
                "桃蚜",
                "桃粉蚜",
                "桃瘤蚜",
                "苹果瘤蚜",
                "油松球蚜",
                "松大蚜",
                "侧柏大蚜",
                "绣线菊蚜",
                "槐蚜",
                "杨白毛蚜",
                "梧桐木虱",
                "槐木虱",
                "梨木虱",
                "黄杨角蜡蚧",
                "月季白轮盾蚧",
                "柿绵蚧",
                "梨圆蚧",
                "草履蚧",
                "桑白蚧",
                "朝鲜球坚蚧",
                "瘤坚大球蚧",
                "水木坚蚧",
                "松牡蛎盾蚧",
                "卫矛矢尖盾蚧",
                "国槐盔蚧",
                "龟蜡蚧",
                "吹绵蚧",
                "紫薇绒蚧",
                "白蜡绵粉蚧",
                "白蜡蚧",
                "松突圆蚧",
                "柳蛎盾蚧",
                "日本龟蜡蚧",
                "绿盲蝽",
                "梨网蝽",
                "苹果叶螨",
                "山楂叶螨",
                "二斑叶螨",
                "茶翅蝽",
                "刺槐叶瘿蚊",
                "光肩星天牛",
                "桃红颈天牛",
                "桑天牛",
                "锈色粒肩天牛",
                "双条杉天牛",
                "松幽天牛",
                "云斑天牛",
                "云杉小墨天牛",
                "双斑锦天牛",
                "青杨天牛",
                "白杨透翅蛾",
                "海棠透翅蛾",
                "松梢螟",
                "苹果吉丁虫",
                "梨金缘吉丁虫",
                "合欢吉丁虫",
                "松迹地吉丁",
                "沟眶象",
                "臭樁沟眶象",
                "柳干木蠹蛾",
                "小线角木蠹蛾",
                "芳香木蠹蛾",
                "松六齿小蠹",
                "松纵坑切梢小蠹",
                "柏肤小蠹",
                "红脂大小蠹",
                "松大象鼻虫",
                "白蜡哈氏茎蜂",
                "杨干象",
                "国槐小卷蛾",
                "栗瘿蜂",
                "日本双棘长蠹",
                "梨小食心虫",
                "桃小食心虫",
                "核桃举肢蛾",
                "柿蒂虫",
                "桃蛀螟",
                "李实蜂",
                "桃仁蜂",
                "梨象鼻虫",
                "白星花金龟",
                "小地老虎",
                "黄地老虎",
                "大灰象甲",
                "沟金针虫",
                "细胸金针虫",
                "东方蝼蛄",
                "黑绒金龟",
                "苹毛金龟",
                "铜绿金龟",
                "朝鲜褐金龟",
                "小青花金龟",
                "大云鳃金龟"};
    }
}
